name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'       
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write
  actions: write
  security-events: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/Commons/Commons/.Commons.csproj

      - name: Build
        run: dotnet build src/Commons/Commons/.Commons.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack src/Commons/Commons/.Commons.csproj --configuration Release --no-build -o ./packages

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.LIB_COMMONS_TOKEN }} --source "github"
